### PR TITLE
Add requires before source reads to ensure EOF happens when exhausted.

### LINKED ISSUE #627: ProtoReader#readVarint64 can throw an IllegalStateException
It needs to defend against the input stream being exhausted.

```
java.lang.IllegalStateException: size == 0
	at okio.Buffer.readByte(Buffer.java:273)
	at com.squareup.wire.ProtoReader.readVarint64(ProtoReader.java:330)
```

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #627.

### CODE REVIEW

**Comment by JakeWharton** [comment]
I can write tests if you want, but it's really just testing a semi-annoyance from Okio.

**Comment by swankjesse** [comment]
Thanks!

**Comment by swankjesse** [comment]
LGTM

**Comment by JakeWharton** [comment]
I think whatever you merged earlier broke the build. Fixing.

**Comment by JakeWharton** [comment]
f9bb5e4448752834ae45cceb8c67e55e61f9d66c

**Comment by swankjesse** [comment]
Yup. I saw an old PR that I’d forgotten to merge. It had an implicit conflict with something else that I’d merged since.

**Comment by swankjesse** [comment]
Thanks!

**Pull request merged**
