### PR TITLE
Complete the switch to JavaPoet by dropping JavaWriter.

### PR DESCRIPTION
**Pull request by swankjesse**
Plus all of the supporting code.

### CODE REVIEW

**Comment by adriancole** [comment]
might want to permute JavaWriter and JavaPoet in the PR desc :)

**Comment by swankjesse** [comment]
Yipes.

**Comment by swankjesse** [comment]
Good to go. I think that landing this in master will kick off the start of a Wire 2.0 push.

**Comment by JakeWharton** [comment]
Crashes mobile Chrome, I'll look in a bit.

**Comment by JakeWharton** [comment]
:100:

**Pull request merged**
