### PR TITLE
Exclude unknown fields when encoding JSON also.

### PR DESCRIPTION
**Pull request by swankjesse**
Follow up to https://github.com/square/wire/pull/515

### CODE REVIEW

**Comment by swankjesse** [comment]
FYI @EddieRingle

**Comment by EddieRingle** [comment]
@swankjesse Ah, you beat me to it. Looks good to me!

**Comment by EddieRingle** [comment]
@swankjesse @JakeWharton Would it be possible to do another bugfix release soon to get this and #515 into the repos without me going through JitPack?

**Comment by JakeWharton** [comment]
Yeah we can do one. I was hoping to take a crack at #507 before the next bugfix, but don't have the time today.

**Pull request merged**
