### PR TITLE
New API: extraTypeAnnotations

### PR DESCRIPTION
**Pull request by swankjesse**
The goal of this new API is to allow users to specify extra annotations that'll apply to the Wire-generated classes. This is specifically useful for the @Immutable annotation offered by Jetpack Compose, and could be useful for other annotations.

### CODE REVIEW

**Comment by JakeWharton** [comment]
The Compose compiler allows you to provide a list of external types that are stable. So if one provided Wire's `Message` I think you wouldn't need this feature (Compose will traverse the hierarchy of a type). Unless there are actually other use cases in mind.

**Comment by oldergod** [comment]
Coil did it a few weeks ago https://github.com/coil-kt/coil/pull/1962/files

**Comment by oldergod** [comment]
Other usecase would be https://github.com/square/wire/issues/807

**Comment by swankjesse** [comment]
I’m going to shelve this for now because I believe the Compose configuration file can solve my immediate problem.

I think there’s potentially something useful for Wire to do to hint to Compose about what’s immutable.

**Comment by autonomousapps** [comment]
> Other usecase would be #807

JaCoCo will automatically excluded generated files from code coverage reports.

**Pull request closed without merging**
