### PR TITLE
[wire-runtime] Explode vararg `args` before passing them to String.format

### PR DESCRIPTION
**Pull request by pavlospt**
Resolves https://github.com/square/wire/issues/1048

### CODE REVIEW

**Comment by oldergod** [comment]
Thanks! How hard would it be to write a test case for that?

**Comment by Egorand** [comment]
I don't think it warrants a test, it's a simple omission and the fix is straightforward.

**Comment by Egorand** [comment]
@pavlospt could you please sign our [CLA](https://spreadsheets.google.com/spreadsheet/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ&ndplr=1) so that I can merge the PR?

**Comment by pavlospt** [comment]
@oldergod I could write test for it but i consider it an overkill since this kind of extensions are rarely changing. 
@Egorand I signed the CLA!

**Comment by JakeWharton** [comment]
It's not the function that needs a test–it's the codepath which invokes it.

**Comment by Egorand** [comment]
I can look into it when I have time. `String.format()` is only used to format an exception message though, so I consider it low priority.

**Comment by JakeWharton** [comment]
The fact that no test invokes the exceptional path is the problem and would have uncovered the problem. We don't actually need to care that much about the actual message.

**Comment by pavlospt** [comment]
@Egorand if you add the bytes & message from this issue: https://github.com/square/wire/issues/1056 i think you have an almost ready test case.

**Pull request merged**
