### PR TITLE
Handle extension name collisions on field options.

### PR DESCRIPTION
**Pull request by swankjesse**

### CODE REVIEW

**Comment by JakeWharton** [comment]
I think you need a rebase on master? The SHA itself passes but the build for testing the merge SHA isn't.

**Comment by JakeWharton** [comment]
LGTM

**Comment by swankjesse** [comment]
Strange. The thing it's failing on is this:
```
Test files changed. Did you run gen_tests.sh?
```
But gen_tests is up-to-date.

**Comment by swankjesse** [comment]
I think Travis was onto something. I think my fields are reordered in different JVMs. Will investigate.

**Pull request merged**
