### PR TITLE
Fix deprecated funs

### PR DESCRIPTION
**Pull request by oldergod**
It's time.

### CODE REVIEW

**Comment by Egorand** [comment]
Needs a major release?

**Comment by oldergod** [comment]
3.5 is next

**Comment by Egorand** [comment]
Major would be 4.0. Not sure though how strict we want to be with breaking the API in `JavaGenerator`, but strictly speaking this kind of change would require 4.0.

**Comment by oldergod** [comment]
I don't think Wire is strict about these. We've broken APIs before without
doing the big change.
Those deprecated are also very old.

2020年10月19日(月) 11:10 Egor Andreevich <notifications@github.com>:

**Comment by oldergod** [comment]
Nevertheless, we could also do a 4.0.

2020年10月19日(月) 11:28 Benoît Quenaudon <oldering@gmail.com>:

**Comment by swankjesse** [comment]
I don’t expect anyone is running JavaGenerator outside of Wire itself. Anyone who is must upgrade to WireRun, as that’s the only thing we really want to maintain.

**Pull request merged**
