### PR TITLE
Make all options of KotlinTarget available in the cli as flags.

### PR DESCRIPTION
**Pull request by elshad-faire**
I am trying to use wire in Bazel to generate protos. I realized that the WireCompiler has limited number of flags that can be configured if I were to subprocess WireCompiler. So it is impossible to generate Kotlin protos with the options I want currently unless I build my own WireCompiler like class which I want to avoid. I just added the rest of the KotlinTarget options as flags where I prefixed them with kotlin_.

This is my first time sending a pr to wire. Please let me know if I need to perform any extra actions. Thanks.

### CODE REVIEW

**Review by oldergod — COMMENTED** [review]
Thanks for the PR. Could you add one test in WireCompilerTests which consumes all new flags?

**Comment by elshad-faire** [comment]
> Thanks for the PR. Could you add one test in WireCompilerTests which consumes all new flags?

@oldergod thanks for the review. Added a test. Let me know if anything else is needed.

**Comment by oldergod** [comment]
Cheers, I'll merge on green

**Comment by elshad-faire** [comment]
> Cheers, I'll merge on green

Thanks! I see there are some build failures and I am not sure if they are related to my change?

**Comment by elshad-faire** [comment]
@oldergod thanks for fixing the build issues. Are you planning to merge the pr soon or is there anything else that needs to be done?

**Comment by elshad-faire** [comment]
@oldergod how is the release policy? Can I expect there to be a new release soon?

I saw https://square.github.io/wire/releasing/. Can anyone request a release?

**Pull request merged**
