### PR TITLE
Implement Maven support for custom type adapters.

### PR DESCRIPTION
**Pull request by swankjesse**

### CODE REVIEW

**Comment by JakeWharton** [comment]
```
/home/travis/build/square/wire/wire-maven-plugin/src/main/java/com/squareup/wire/mojo/ProtoAdapterParameter.java:28:48: Extra HTML tag found: </protoType>
/home/travis/build/square/wire/wire-maven-plugin/src/main/java/com/squareup/wire/mojo/ProtoAdapterParameter.java:29:34: Extra HTML tag found: </javaName>
/home/travis/build/square/wire/wire-maven-plugin/src/main/java/com/squareup/wire/mojo/ProtoAdapterParameter.java:30:67: Extra HTML tag found: </adapter>
/home/travis/build/square/wire/wire-maven-plugin/src/main/java/com/squareup/wire/mojo/ProtoAdapterParameter.java:31:6: Extra HTML tag found: </protoAdapter>
```
Looks like you need some `&lt;`s spread on.

**Comment by JakeWharton** [comment]
lgtm though

**Comment by swankjesse** [comment]
Ugh, that’s a checkstyle bug. The `<` is safe; it’s guarded by a `{@code` block.

Fixed by turning off the broken checkstyle check:
```
    <module name="JavadocStyle">
      <property name="checkHtml" value="false"/>
    </module>
```

**Comment by swankjesse** [comment]
https://github.com/checkstyle/checkstyle/issues/3351

**Pull request merged**
