### PR TITLE
.proto enum variable named the same as enumerator causes compilation error #299 (Kotlin version for Java pull request #1252)

### PR DESCRIPTION
**Pull request by mellster2012**

### CODE REVIEW

**Comment by oldergod** [comment]
You probably created this PR by mistake so I'm closing it.

**Comment by mellster2012** [comment]
@oldergod The Kotlin generator has the same issue when producing Kotlin sources (they don't compile if type name is the same as variable name), I don't know if you already incorporated a fix for Kotlin, that's why I provided it.

**Comment by oldergod** [comment]
Oops !

**Comment by oldergod** [comment]
Then please, fix the conflict.

**Comment by mellster2012** [comment]
@oldergod see https://github.com/square/wire/pull/1276

**Pull request closed without merging**
