### PR TITLE
Improve WireTask cacheability by storing project-relative paths instead of absolute ones in the task inputs

### LINKED ISSUE #1859: WireTask uses non-normalized paths and breaks Gradle build caching
After doing some simple local build caching tests with the same project in multiple locations, build scans revealed that `WireTask` is not up to date when it should be due to using non-normalized paths in its `transforms` property

Namely - `outDirectory`

Output from a simple snippet to print it

```kotlin
tasks.withType<WireTask>().configureEach {
  doFirst { println(transforms) }
}
```

```
KotlinTarget(includes=[*], excludes=[], exclusive=true, outDirectory=/Users/zsweers/dev/slack/slack-android-ng/telemetry-definitions/build/generated/source/wire, android=false, javaInterop=false, emitDeclaredOptions=true, emitAppliedOptions=false, rpcCallStyle=SUSPENDING, rpcRole=CLIENT, singleMethodServices=false)
```

### PR DESCRIPTION
**Pull request by staktrace**
Fixes #1859

### CODE REVIEW

**Comment by staktrace** [comment]
(I was unable to run `./gradlew clean check` locally because it needed an android SDK or something, so I'm making a PR and hoping the CI will tell me if I screwed something up)

**Comment by staktrace** [comment]
I'll try to write a test as well.

**Comment by staktrace** [comment]
I discussed this further with @swankjesse. One idea he had which we tried implementing was to just always have the `Target.outDirectory` field be relative to `$CWD`. However the problem with that is that the relative path may still contain things like the project name which breaks cacheability. In particular the test I added still failed in that case because the `Target.outDirectory` was `wire-gradle-plugin/src/test/projects/cache-relocation-1/src/main/proto` for one project and `wire-gradle-plugin/src/test/projects/cache-relocation-2/src/main/proto` for the other project, breaking cacheability.

Therefore the `Target.outDirectory` does need to be relative to the project directory, and to make the aesthetics of the API nicer he suggested replace the `resolveOutDirectory` function in my original implementation with a more generic `copyTarget` function. Updated patches with that change coming up shortly.

**Review by swankjesse — APPROVED** [review]
Great PR. Thank you!

**Comment by staktrace** [comment]
Not really sure why github actions is just cancelling checks instead of running them.. it was green earlier so I'm going to merge and hope for the best!

**Pull request merged**
