### PR TITLE
Shade the compiler.

### PR DESCRIPTION
**Pull request by swankjesse**
Closes https://github.com/square/wire/issues/172

### CODE REVIEW

**Comment by swankjesse** [comment]
This only shades the CLI interface. Is that the right target?

**Comment by swankjesse** [comment]
Notably, it doesn't shade the Wire internals. So if you want to use the Wire CLI and the Wire Java API in the same gradle plugin, you might still suffer a conflict.

**Comment by JakeWharton** [comment]
This actually might no longer be necessary due to all the architectural changes that were made.

**Comment by JakeWharton** [comment]
We can always revisit post-2.0 if it turns out to be necessary.

**Comment by swankjesse** [comment]
Deal.

**Pull request closed without merging**
