### PR TITLE
Add test to check for naming conflict with android.os.Parcelable.Creator

### PR DESCRIPTION
**Pull request by EddieRingle**
Not sure how useful this is, but I've taken the current generated output for a `Creator` message and replaced simple usages of `Creator` with the fully-qualified name of the message instead and added it as a test.

RE: square/wire#475

### CODE REVIEW

**Comment by JakeWharton** [comment]
Cool. I think bumping to the latest JavaPoet (which would need a release) should fix this. You can test if you want by referencing 1.4.0-SNAPSHOT

**Comment by EddieRingle** [comment]
@JakeWharton It doesn't appear that JavaPoet 1.4 resolves this.

**Comment by JakeWharton** [comment]
Doh. Well that's unfortunate.

**Comment by swankjesse** [comment]
So the problem here is that JavaPoet doesn’t consider that `Creator` is nested in the implemented interface `Parcelable`, and _that_ `Creator` takes precedence over the self-type `Creator`. We need to fix this in JavaPoet.

**Comment by swankjesse** [comment]
https://github.com/square/javapoet/issues/77

**Comment by swankjesse** [comment]
(This test belongs in JavaPoet. If you'd like to submit there, please do.)

**Pull request closed without merging**
