### PR TITLE
Omit MessageType from the @ProtoField annotation.

### PR DESCRIPTION
**Pull request by swankjesse**
It's not much more work to get it from the field itself, and it will
work better if we support custom wire adapters.

### CODE REVIEW

**Comment by danrice-square** [comment]
@swankjesse We added the annotation parameter to work around a limitation of reflection support in j2objc, which we were attempting to use to translate Wire code. Unless someone is actively still trying to use Wire with obj2c I think it's fine to make this change.

**Comment by swankjesse** [comment]
Ah, thanks Dan. I think the right solution for Objective C users is to teach Wire to emit nice Objective C code directly.

**Comment by JakeWharton** [comment]
Or to use a `--no-reflection` flag to emit fully-formed adapters.

**Comment by JakeWharton** [comment]
And I think we want to aspire to both.

**Pull request merged**
